### ISSUE TITLE
Add full support for handling Qbs configurations

### ISSUE THREAD

**Issue by viprip** [StoiridhProject/StoiridhTools#31]
**Introduction**

A Qbs configuration is a persistent configuration file that contains profiles about compilers and Qt versions. Regrouping those Qbs configurations, we can display the profiles with one command, update the preferences, e.g. the qbsSearchPaths settings, either for all profiles or for a specific profile, and so on. Below, a non-exhaustive list of what we can implement in the future.

**Tasks:**

- [ ] Qbs configuration file: (Add common I/O operations)
 * [ ] create
 * [ ] read
 * [ ] write (update?)
- [ ] CLI:
 * [ ] display all Qbs configuration files plus their locations
 * [ ] Profiles:
   - [ ] display all Qbs profiles
    - [ ] display all Qbs profiles from a specific Qbs configuration
    - [ ] allow to rename a profile
- [ ] Stòiridh Tools' configuration:
 * [ ] save the locations of those Qbs configuration files
